name: ht_countries_inmemory
description: An in memory implementation of the ht_countries_client package.
repository: https://github.com/headlines-toolkit/ht-countries-inmemory
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  ht_countries_client:
    git:
      url: https://github.com/headlines-toolkit/ht-countries-client.git

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
